name: pefile
description: A Dart library to parse Portable Executable (PE) format
version: 1.0.0-dev.1
homepage: https://github.com/Midi12/pefile
repository: https://github.com/Midi12/pefile

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
